---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: designate_pre_install.yml
- include: designate_install.yml
- include: designate_post_install.yml
- include: designate_upstart_init.yml

- include: designate_db_setup.yml
  when: >
    inventory_hostname == groups['designate_all'][0]

- include: designate_service_setup.yml
  when: >
    inventory_hostname == groups['designate_all'][0]

- name: Flush handlers
  meta: flush_handlers


